package com.waffae.pancake.model;

public class User {
    private String userid;
    

    private String username;

    private String enname;
    
    private String createtime;
    
    private Role role;
    
    public Role getRole() {
		return role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public String getCreatetime() {
		return createtime;
	}

	public void setCreatetime(String createtime) {
		this.createtime = createtime;
	}

	public String toString(){
    	return this.userid+"-"+this.username+"-"+this.enname;
    }

    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userId
     *
     * @param userid the value for user.userId
     *
     * @mbggenerated Tue May 14 11:14:49 CST 2013
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userName
     *
     * @return the value of user.userName
     *
     * @mbggenerated Tue May 14 11:14:49 CST 2013
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userName
     *
     * @param username the value for user.userName
     *
     * @mbggenerated Tue May 14 11:14:49 CST 2013
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.enName
     *
     * @return the value of user.enName
     *
     * @mbggenerated Tue May 14 11:14:49 CST 2013
     */
    public String getEnname() {
        return enname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.enName
     *
     * @param enname the value for user.enName
     *
     * @mbggenerated Tue May 14 11:14:49 CST 2013
     */
    public void setEnname(String enname) {
        this.enname = enname;
    }
}